import { Eye, EyeOff, ArrowUpRight, Check } from 'lucide-react'
import { useState } from 'react'
import { authenticateDemoUser, saveUser, getUser } from '../auth'

type AuthPageProps = { mode: 'signin' | 'signup' | 'forgot'; navigate: (path: string) => void }

export default function AuthPages({ mode, navigate }: AuthPageProps) {
  const destination = sessionStorage.getItem('genra-auth-destination') || '/dashboard'
  const [showPassword, setShowPassword] = useState(false)
  const [email, setEmail] = useState('')
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [fullName, setFullName] = useState('')
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)
  const [busy, setBusy] = useState(false)

  const complete = (name: string, address: string) => { saveUser({ name, email: address }); authenticateDemoUser(); sessionStorage.removeItem('genra-auth-destination'); navigate(destination) }
  const submitSignIn = (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!email.trim()) return setError('Please enter your email or username.'); if (!password) return setError('Please enter your password.'); const stored = getUser(); const valid = (email.trim().toLowerCase() === 'demo@genra.ai' && password === 'Genra123') || (stored && email.trim().toLowerCase() === stored.email.toLowerCase() && password === 'Genra123'); if (!valid) return setError('Use demo@genra.ai / Genra123 for this prototype.'); setBusy(true); window.setTimeout(() => complete(stored?.name || 'Demo User', email.trim()), 450) }
  const submitSignUp = (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!fullName.trim() || !username.trim() || !email.trim() || !password || !confirm) return setError('Please complete every required field.'); if (!/^\S+@\S+\.\S+$/.test(email)) return setError('Please enter a valid email address.'); if (password.length < 6) return setError('Password must be at least 6 characters.'); if (password !== confirm) return setError('Passwords must match.'); setBusy(true); window.setTimeout(() => complete(fullName.trim(), email.trim()), 450) }
  const submitForgot = (event: React.FormEvent) => { event.preventDefault(); setError(''); if (!/^\S+@\S+\.\S+$/.test(email)) return setError('Please enter a valid email address.'); setSuccess(true) }
  const google = () => complete('Demo Creator', 'demo.creator@gmail.com')
  if (mode === 'forgot') return <AuthLayout><span className="auth-kicker">GENRA / ACCOUNT RECOVERY</span><h1>Forgot your password?</h1>{success ? <div className="auth-success"><Check size={18} /><p>If this were production, a reset link would be sent to your email. For this demo, your account is ready to continue.</p><button className="auth-link-button" onClick={() => navigate('/signin')}>Back to Sign In <ArrowUpRight size={14} /></button></div> : <form onSubmit={submitForgot}><p>Enter your email and we'll help you reset your password.</p><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@company.com" /></label>{error && <span className="auth-error">{error}</span>}<button className="auth-submit" type="submit">Send Reset Link <ArrowUpRight size={15} /></button><button className="auth-link-button" type="button" onClick={() => navigate('/signin')}>Back to Sign In</button></form>}</AuthLayout>
  if (mode === 'signup') return <AuthLayout><span className="auth-kicker">GENRA / CREATE ACCOUNT</span><h1>Create Account</h1><p>Build your place in the AI-native creative network.</p><form onSubmit={submitSignUp}><label>Full Name<input value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} /><button className="password-toggle" type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Show or hide password">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></label><label>Confirm Password<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} /></label>{error && <span className="auth-error">{error}</span>}<button className="auth-submit" type="submit" disabled={busy}>{busy ? 'Creating account...' : <>Create Account <ArrowUpRight size={15} /></>}</button><button className="auth-google" type="button" onClick={google}>Continue with Google</button></form><p className="auth-foot">Already have an account? <button className="auth-inline-link" onClick={() => navigate('/signin')}>Sign In</button></p></AuthLayout>
  return <AuthLayout><span className="auth-kicker">GENRA / DEMO ACCESS</span><h1>Welcome back</h1><p>Sign in to continue to Genra.</p><form onSubmit={submitSignIn}><label>Email or Username<input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="demo@genra.ai" /></label><label>Password<input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Genra123" /><button className="password-toggle" type="button" onClick={() => setShowPassword(!showPassword)} aria-label="Show or hide password">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></label>{error && <span className="auth-error">{error}</span>}<button className="auth-submit" type="submit" disabled={busy}>{busy ? 'Signing in...' : <>Sign In <ArrowUpRight size={15} /></>}</button><button className="auth-google" type="button" onClick={google}>Continue with Google</button></form><button className="auth-link-button" onClick={() => navigate('/forgot-password')}>Forgot password?</button><p className="auth-foot">Don't have an account? <button className="auth-inline-link" onClick={() => navigate('/create-account')}>Create Account</button></p></AuthLayout>
}

function AuthLayout({ children }: { children: React.ReactNode }) { return <div className="auth-page"><div className="auth-card"><button className="auth-logo" onClick={() => { window.history.pushState({}, '', '/'); window.dispatchEvent(new PopStateEvent('popstate')) }}>GENRA</button>{children}</div></div> }
