import { ArrowUpRight, BadgeCheck, Menu, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { gradientPosters } from '../data/assets'
import { isAuthenticated } from '../auth'

type HomeProps = { navigate: (path: string) => void; onStudioClick: () => void; onSignIn: () => void; onGetStarted: () => void }
type HomeCreator = { id: string; name: string; specialty: string; mark: string; tools: string[]; gradient: string }

const homeCreators: HomeCreator[] = [
  { id: 'kenji-park', name: 'Kenji Park', specialty: 'AI Video Director', mark: 'KP', tools: ['Kling', 'Sora', 'Topaz'], gradient: gradientPosters[2] },
  { id: 'maya-chen', name: 'Maya Chen', specialty: 'AI Product Visuals', mark: 'MC', tools: ['Flux', 'Veo', 'ComfyUI'], gradient: gradientPosters[0] },
  { id: 'arjun-rao', name: 'Arjun Rao', specialty: 'AI Motion Designer', mark: 'AR', tools: ['Runway', 'Kling', 'After Effects'], gradient: gradientPosters[3] },
  { id: 'sofia-lee', name: 'Sofia Lee', specialty: 'AI Creative Director', mark: 'SL', tools: ['Midjourney', 'Sora', 'Flux'], gradient: gradientPosters[4] },
]

export default function HomePage({ navigate, onStudioClick, onSignIn, onGetStarted }: HomeProps) {
  const [menuOpen, setMenuOpen] = useState(false)
  const accountAction = isAuthenticated() ? () => navigate('/dashboard') : onSignIn
  const links = [['Discover', '/creators'], ['Creators', '/creators'], ['Brands', '/briefs'], ['AI Studio', '/studio'], ['Projects', '/dashboard']]
  return <div className="home-page">
    <header className="home-nav"><button className="home-wordmark" onClick={() => navigate('/')} aria-label="Genra home">GENRA</button><nav className={menuOpen ? 'home-nav-links open' : 'home-nav-links'}>{links.map(([label, path]) => <button key={label} onClick={() => { if (path === '/studio') onStudioClick(); else navigate(path); setMenuOpen(false) }}>{label}</button>)}</nav><div className="home-nav-actions"><button className="home-signin" onClick={accountAction}>{isAuthenticated() ? 'Dashboard' : 'Sign In'}</button><button className="home-get-started" onClick={onGetStarted}>Get Started <ArrowUpRight size={14} /></button><button className="home-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu size={18} /></button></div></header>
    <section className="home-hero"><span className="home-kicker">AI CREATOR MARKETPLACE</span><h1>The creative marketplace<br />for the <em>AI era.</em></h1><p>Discover AI creators, connect with brands, and create with powerful AI tools — all in one place.</p><div className="home-hero-actions"><button className="home-primary" onClick={() => navigate('/creators')}>Explore Genra <ArrowUpRight size={15} /></button><button className="home-secondary" onClick={onStudioClick}>Open AI Studio <Sparkles size={15} /></button></div></section>
    <section className="home-entry-section section-pad"><div className="home-entry-grid"><HomeEntryCard label="FOR CREATORS" title="Show what you can create." description="Build your profile, showcase your workflow and get discovered by brands." button="Join as Creator" gradient={gradientPosters[2]} navigate={navigate} path="/dashboard" mark="01" /><HomeEntryCard label="FOR BRANDS" title="Find the right AI creator." description="Discover creators by skills, AI tools, specialization, workflow and commercial rights." button="Find Creators" gradient={gradientPosters[0]} navigate={navigate} path="/creators" mark="02" /><HomeEntryCard label="AI STUDIO" title="Create with AI." description="Generate images, videos, motion and creative edits in one workspace." button="Open AI Studio" gradient={gradientPosters[3]} navigate={navigate} path="/studio" mark="03" studio onNavigate={onStudioClick} /></div></section>
    <section className="home-featured section-pad"><div className="home-section-head"><div><span className="home-kicker">THE CREATOR INDEX</span><h2>Featured AI <em>Creators</em></h2></div><div><p>Discover creators by their tools, skills and creative process.</p><button className="home-link" onClick={() => navigate('/creators')}>View all creators <ArrowUpRight size={14} /></button></div></div><div className="home-creator-grid">{homeCreators.map((creator) => <HomeCreatorCard key={creator.id} creator={creator} navigate={navigate} />)}</div></section>
    <section className="home-how section-pad"><div className="home-section-head"><div><span className="home-kicker">THE GENRA METHOD</span><h2>How Genra <em>Works</em></h2></div><p>One platform. Three ways to create.</p></div><div className="home-steps"><HomeStep number="01" title="Discover" text="Find AI creators that match your project." /><span className="home-step-line" /><HomeStep number="02" title="Brief" text="Define your content, style, format and commercial rights." /><span className="home-step-line" /><HomeStep number="03" title="Create" text="Collaborate and produce the final creative." /></div></section>
    <section className="home-studio section-pad"><div className="home-studio-copy"><span className="home-kicker">GENRA AI STUDIO</span><h2>Your AI creative <em>workspace.</em></h2><p>Turn ideas into images, videos and motion with Genra AI Studio.</p><button className="home-primary" onClick={onStudioClick}>Explore AI Studio <ArrowUpRight size={15} /></button></div><div className="home-studio-mock"><div className="studio-mock-top"><span>GENRA AI STUDIO</span><span><i /> 120 credits</span></div><div className="studio-mock-body"><div className="studio-mock-controls"><span className="mock-label">CREATE</span><strong>What do you<br />want to make?</strong><div className="mock-input">Describe your visual idea...</div><div className="mock-selects"><span>Genra Vision</span><span>9:16</span></div><div className="mock-cta">Generate <Sparkles size={12} /></div></div><div className="studio-mock-canvas"><div className="mock-orb" /><span>Your canvas is ready.</span></div></div><div className="studio-mock-footer"><span>Recent creations</span><div><b style={{ background: gradientPosters[0] }} /><b style={{ background: gradientPosters[2] }} /><b style={{ background: gradientPosters[4] }} /></div></div></div></section>
    <section className="home-duo section-pad"><HomeDuoCard label="FOR BRANDS" title="Find creators who fit your vision." description="Search by AI tools, skills, workflow, specialization and commercial rights." button="Explore Creators" navigate={navigate} path="/creators" gradient={gradientPosters[4]} /><HomeDuoCard label="FOR CREATORS" title="Show how you create." description="Showcase your work, workflow, tools and commercial rights." button="Join Genra" navigate={navigate} path="/dashboard" gradient={gradientPosters[1]} /></section>
    <section className="home-final"><span className="home-kicker">THE NEXT FRAME</span><h2>What will you <em>create next?</em></h2><p>Find a creator, start a project, or create with AI.</p><div><button className="home-primary" onClick={() => navigate('/dashboard')}>I'm a Creator <ArrowUpRight size={15} /></button><button className="home-secondary" onClick={() => navigate('/briefs/new')}>I'm a Brand <ArrowUpRight size={15} /></button><button className="home-secondary" onClick={onStudioClick}>Open AI Studio <Sparkles size={15} /></button></div></section>
  </div>
}

function HomeEntryCard({ label, title, description, button, gradient, navigate, path, mark, studio = false, onNavigate }: { label: string; title: string; description: string; button: string; gradient: string; navigate: (path: string) => void; path: string; mark: string; studio?: boolean; onNavigate?: () => void }) { return <article className={studio ? 'home-entry-card studio-card' : 'home-entry-card'}><div className="home-entry-visual" style={{ background: gradient }}><div className="home-entry-gridlines" /><span className="home-entry-mark">{mark}</span>{studio && <div className="home-entry-ui"><span /><span /><span /></div>}<span className="home-entry-arrow"><ArrowUpRight size={17} /></span></div><div className="home-entry-copy"><span className="home-kicker">{label}</span><h3>{title}</h3><p>{description}</p><button className="home-link" onClick={onNavigate || (() => navigate(path))}>{button} <ArrowUpRight size={14} /></button></div></article> }
function HomeCreatorCard({ creator, navigate }: { creator: HomeCreator; navigate: (path: string) => void }) { return <article className="home-creator-card"><button className="home-creator-visual" style={{ background: creator.gradient }} onClick={() => navigate(`/creators/${creator.id}`)}><span>{creator.mark}</span><i><ArrowUpRight size={16} /></i></button><div className="home-creator-copy"><div><h3>{creator.name}</h3><span>{creator.specialty}</span></div><div className="home-badges"><span><BadgeCheck size={11} /> Verified</span><span>Workflow Shown</span><span>Commercial Rights</span></div><div className="home-tools">{creator.tools.map((tool) => <span key={tool}>{tool}</span>)}</div></div></article> }
function HomeStep({ number, title, text }: { number: string; title: string; text: string }) { return <div className="home-step"><span>{number}</span><h3>{title}</h3><p>{text}</p></div> }
function HomeDuoCard({ label, title, description, button, navigate, path, gradient }: { label: string; title: string; description: string; button: string; navigate: (path: string) => void; path: string; gradient: string }) { return <article className="home-duo-card"><div className="home-duo-visual" style={{ background: gradient }}><span className="home-entry-gridlines" /><strong>{label === 'FOR BRANDS' ? 'B' : 'C'}</strong></div><div><span className="home-kicker">{label}</span><h3>{title}</h3><p>{description}</p><button className="home-link" onClick={() => navigate(path)}>{button} <ArrowUpRight size={14} /></button></div></article> }
