export const creators = [
  { _id: 'mara-lennox', name: 'Mara Lennox', handle: '@maralennox', headline: 'Cinematic product worlds for brands with a point of view.', location: 'London', specializations: ['product-film', 'brand-identity', '3d-render'], skills: ['art direction', 'motion design', 'generative film'], tools: [{ name: 'Runway', kind: 'video', verified: true }, { name: 'Veo', kind: 'video', verified: true }, { name: 'ComfyUI', kind: 'workflow', verified: true }, { name: 'After Effects', kind: 'upscale', verified: true }], contentTypes: ['video-ad', 'brand-film'], formats: ['16:9', '9:16', '1:1'], availability: 'open', pricing: { from: 2400, currency: 'USD', unit: 'per-project' }, commercialUse: true, verification: { toolsVerified: true, workflowVerified: true, pastWorkVerified: true, score: 97 } },
  { _id: 'kenji-park', name: 'Kenji Park', handle: '@kenjipark', headline: 'Surreal motion systems for fashion, culture, and music.', location: 'Seoul', specializations: ['fashion', 'motion-graphics', 'music-video'], skills: ['motion systems', 'sound design', 'art direction'], tools: [{ name: 'Kling', kind: 'video', verified: true }, { name: 'Sora', kind: 'video', verified: true }, { name: 'Suno', kind: 'audio', verified: true }, { name: 'Topaz', kind: 'upscale', verified: true }], contentTypes: ['animation', 'social-loop'], formats: ['9:16', '16:9', '4:5'], availability: 'limited', pricing: { from: 1800, currency: 'USD', unit: 'per-project' }, commercialUse: true, verification: { toolsVerified: true, workflowVerified: true, pastWorkVerified: true, score: 91 } },
  { _id: 'joa-velasquez', name: 'Joa Velásquez', handle: '@joavfx', headline: 'Playful character animation with an editorial edge.', location: 'Mexico City', specializations: ['character-animation', 'social-shorts', 'brand-identity'], skills: ['character design', 'storyboarding', 'voice direction'], tools: [{ name: 'Midjourney', kind: 'image', verified: true }, { name: 'Runway', kind: 'video', verified: true }, { name: 'ElevenLabs', kind: 'audio', verified: true }, { name: 'Flux', kind: 'image', verified: false }], contentTypes: ['animation', 'social-loop'], formats: ['9:16', '1:1', '4:5'], availability: 'open', pricing: { from: 1250, currency: 'USD', unit: 'per-project' }, commercialUse: true, verification: { toolsVerified: true, workflowVerified: true, pastWorkVerified: false, score: 84 } },
  { _id: 'rhea-okafor', name: 'Rhea Okafor', handle: '@rheaokafor', headline: 'High-gloss visual worlds, built for the scroll.', location: 'New York', specializations: ['social-shorts', 'product-film', 'fashion'], skills: ['short-form', 'creative testing', 'product styling'], tools: [{ name: 'Flux', kind: 'image', verified: false }, { name: 'Veo', kind: 'video', verified: true }, { name: 'Topaz', kind: 'upscale', verified: true }], contentTypes: ['video-ad', 'social-loop'], formats: ['9:16', '1:1'], availability: 'open', pricing: { from: 980, currency: 'USD', unit: 'per-project' }, commercialUse: true, verification: { toolsVerified: true, workflowVerified: false, pastWorkVerified: false, score: 78 } },
  { _id: 'adrien-sol', name: 'Adrien Sol', handle: '@adriensol', headline: 'Minimalist 3D, luminous materials, quiet confidence.', location: 'Paris', specializations: ['3d-render', 'brand-identity', 'product-film'], skills: ['3D art direction', 'materials', 'lighting'], tools: [{ name: 'Blender', kind: '3d', verified: true }, { name: 'ComfyUI', kind: 'workflow', verified: true }, { name: 'After Effects', kind: 'upscale', verified: true }], contentTypes: ['video-ad', 'graphic'], formats: ['16:9', '1:1', '21:9'], availability: 'booked', pricing: { from: 3200, currency: 'USD', unit: 'per-project' }, commercialUse: true, verification: { toolsVerified: true, workflowVerified: true, pastWorkVerified: true, score: 99 } },
  { _id: 'nina-ibarra', name: 'Nina Ibarra', handle: '@ninaibarra', headline: 'Human-scale stories from machine-made ingredients.', location: 'Barcelona', specializations: ['brand-identity', 'social-shorts', 'cinematic'], skills: ['documentary', 'storytelling', 'editorial'], tools: [{ name: 'Runway', kind: 'video', verified: true }, { name: 'Sora', kind: 'video', verified: true }, { name: 'ElevenLabs', kind: 'audio', verified: true }], contentTypes: ['brand-film', 'social-loop'], formats: ['16:9', '9:16', '4:5'], availability: 'limited', pricing: { from: 1500, currency: 'USD', unit: 'per-project' }, commercialUse: true, verification: { toolsVerified: true, workflowVerified: true, pastWorkVerified: false, score: 88 } },
]

export const briefs = [
  { _id: 'brief-01', title: 'A new kind of morning', brand: { name: 'Aster & Co.', company: 'Aster & Co.', contactEmail: 'hello@aster.example' }, status: 'published', contentType: 'brand-film', style: ['cinematic', 'minimal'], formats: ['16:9', '9:16'], requiredTools: ['Veo', 'ComfyUI'], budget: { min: 8000, max: 12000, currency: 'USD' }, deadline: '2026-11-18', usage: { commercialUse: true, channels: ['paid-social', 'web'], territories: ['Global'], durationMonths: 12, exclusivity: false, requireProvenance: true } },
  { _id: 'brief-02', title: 'Motion with a pulse', brand: { name: 'Vanta Records', company: 'Vanta Records', contactEmail: 'creative@vanta.example' }, status: 'in-review', contentType: 'music-video', style: ['surreal', '3d-glossy'], formats: ['16:9', '1:1', '9:16'], requiredTools: ['Kling', 'Suno'], budget: { min: 5000, max: 8000, currency: 'USD' }, deadline: '2026-12-03', usage: { commercialUse: true, channels: ['web', 'ooh'], territories: ['Global'], durationMonths: 24, exclusivity: false, requireProvenance: true } },
  { _id: 'brief-03', title: 'Objects of attention', brand: { name: 'Northline Studio', company: 'Northline Studio', contactEmail: 'studio@northline.example' }, status: 'awarded', contentType: 'video-ad', style: ['minimal', '3d-glossy'], formats: ['1:1', '4:5'], requiredTools: ['Blender', 'Flux'], budget: { min: 3000, max: 5000, currency: 'USD' }, deadline: '2026-10-29', usage: { commercialUse: true, channels: ['paid-social', 'web'], territories: ['US', 'EU'], durationMonths: 12, exclusivity: true, requireProvenance: true } },
]
